### PR TITLE
Add secret parameters

### PR DESCRIPTION
**Pull request by cosmo0920**

### CODE REVIEW

**Comment by repeatedly** [comment]
Maybe, `shared_key` should also be secret?

**Comment by cosmo0920** [comment]
Well, if you put it that way, sure.

**Comment by tagomoris** [comment]
@cosmo0920  Please use `secret: true` style hash as same with other part of plugin code.

**Comment by cosmo0920** [comment]
I've unified with `secret: true` style!

**Comment by tagomoris** [comment]
:+1:

**Comment by tagomoris** [comment]
I'll release v0.3.3 after check of some other issue (including #22)

**Comment by repeatedly** [comment]
I release new version including config_section secret fix.
We can merge this.

**Pull request merged**
